/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/Bin/AngryBird_Demo/al_ip/birdf.v
 ** Date	:	2020 11 13
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module bird ( doa, dia, addra, cea, clka, wea );

	output [23:0] doa;

	input  [23:0] dia;
	input  [11:0] addra;
	input  wea;
	input  cea;
	input  clka;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(24),
				.ADDR_WIDTH_A(12),
				.DATA_DEPTH_A(3600),
				.DATA_WIDTH_B(24),
				.ADDR_WIDTH_B(12),
				.DATA_DEPTH_B(3600),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../../../12/SparkRoad_demo参考例程 (2)/8_VGA_Demo/bird.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({24{1'b0}}),
				.addra(addra),
				.addrb({12{1'b0}}),
				.cea(cea),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule